# -*- coding: utf-8 -*-
"""Pothole.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4NVchDbcuJQNj0ksXxUPUDHw0bwWzfl
"""

pip install opendatasets

import opendatasets as od
od.download("https://www.kaggle.com/datasets/dextergoes/pothole-sensor-data")

import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from geopy.distance import geodesic
import joblib

print("Libraries Loaded Successfully")

base_path = "/content/pothole-sensor-data"

pothole_path = os.path.join(base_path, "Pothole")
road_path = os.path.join(base_path, "RoadCondition")

def load_folder_data(folder_path, label_name):
    data_list = []
    for file in os.listdir(folder_path):
        if file.endswith(".csv"):
            df = pd.read_csv(os.path.join(folder_path, file))
            df["label"] = label_name
            data_list.append(df)
    return pd.concat(data_list, ignore_index=True)

pothole_data = load_folder_data(pothole_path, "pothole")
road_data = load_folder_data(road_path, "normal")

data = pd.concat([pothole_data, road_data], ignore_index=True)

print("Dataset Loaded Successfully")
print("Total rows:", len(data))
data.head()

# ONLY sensor features
X = data[[
    "accelerometerX",
    "accelerometerY",
    "accelerometerZ",
    "gyroX",
    "gyroY",
    "gyroZ"
]].copy()

y = data["label"].copy()

print("X columns:")
print(X.columns)

print("\nData types:")
print(X.dtypes)

encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

print("Label Mapping:")
for i, label in enumerate(encoder.classes_):
    print(label, "->", i)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

print("X_train columns:")
print(X_train.columns)

print("\nData types:")
print(X_train.dtypes)

model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

print("Model Training Completed")

y_pred = model.predict(X_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# --------------------------------------------
# Improved Window-based Feature Engineering
# --------------------------------------------

window_size = 80   # You can tune this later

feature_rows = []
labels = []

for i in range(0, len(data) - window_size, window_size):

    window = data.iloc[i:i+window_size]

    # Extract sensor columns
    ax = window["accelerometerX"]
    ay = window["accelerometerY"]
    az = window["accelerometerZ"]
    gx = window["gyroX"]
    gy = window["gyroY"]
    gz = window["gyroZ"]

    # Feature calculations
    features = {
        # Mean features
        "ax_mean": ax.mean(),
        "ay_mean": ay.mean(),
        "az_mean": az.mean(),

        # Standard deviation
        "ax_std": ax.std(),
        "ay_std": ay.std(),
        "az_std": az.std(),

        # Max / Min
        "az_max": az.max(),
        "az_min": az.min(),

        # NEW FEATURES
        "ax_max": ax.max(),
        "ay_max": ay.max(),
        "az_rms": np.sqrt((az ** 2).mean()),
        "gx_mean": gx.mean(),
        "gy_mean": gy.mean(),
        "gz_mean": gz.mean(),

        # Gyro variation
        "gx_std": gx.std(),
        "gy_std": gy.std(),
        "gz_std": gz.std(),
    }

    # Majority label inside window
    label = window["label"].mode()[0]

    feature_rows.append(features)
    labels.append(label)

# Convert to DataFrame
X_window = pd.DataFrame(feature_rows)
y_window = pd.Series(labels)

print("Windowed dataset shape:", X_window.shape)
print("\nClass distribution:")
print(y_window.value_counts())

encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y_window)

X_train, X_test, y_train, y_test = train_test_split(
    X_window,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

print("Model Training Completed")

y_pred = model.predict(X_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

import numpy as np
import pandas as pd

window_size = 80
step_size = 40   # 50% overlap

feature_rows = []
labels = []

for i in range(0, len(data) - window_size, step_size):

    window = data.iloc[i:i+window_size]

    ax = window["accelerometerX"]
    ay = window["accelerometerY"]
    az = window["accelerometerZ"]
    gx = window["gyroX"]
    gy = window["gyroY"]
    gz = window["gyroZ"]

    # 🔥 Magnitude features
    acc_mag = np.sqrt(ax**2 + ay**2 + az**2)
    gyro_mag = np.sqrt(gx**2 + gy**2 + gz**2)

    features = {
        # Mean
        "ax_mean": ax.mean(),
        "ay_mean": ay.mean(),
        "az_mean": az.mean(),

        # Std
        "ax_std": ax.std(),
        "ay_std": ay.std(),
        "az_std": az.std(),

        # Min/Max
        "az_max": az.max(),
        "az_min": az.min(),
        "ax_max": ax.max(),
        "ay_max": ay.max(),

        # RMS
        "az_rms": np.sqrt((az ** 2).mean()),

        # 🔥 Magnitude stats
        "acc_mag_mean": acc_mag.mean(),
        "acc_mag_std": acc_mag.std(),
        "acc_mag_max": acc_mag.max(),

        "gyro_mag_mean": gyro_mag.mean(),
        "gyro_mag_std": gyro_mag.std(),

        # 🔥 Peak features
        "az_peak_to_peak": az.max() - az.min(),
        "acc_peak": acc_mag.max(),

        # 🔥 Energy features
        "az_energy": np.sum(az**2) / len(az),
        "acc_energy": np.sum(acc_mag**2) / len(acc_mag),

        # Gyro stats
        "gx_mean": gx.mean(),
        "gy_mean": gy.mean(),
        "gz_mean": gz.mean(),
        "gx_std": gx.std(),
        "gy_std": gy.std(),
        "gz_std": gz.std(),
    }

    label = window["label"].mode()[0]

    feature_rows.append(features)
    labels.append(label)

X_window = pd.DataFrame(feature_rows)
y_window = pd.Series(labels)

print("Shape:", X_window.shape)
print(y_window.value_counts())

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_window)

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_window, test_size=0.2, random_state=42
)

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Improved Accuracy:", accuracy)

pip install geocoder firebase-admin

import geocoder

def get_location():
    g = geocoder.ip('me')
    return g.latlng  # [latitude, longitude]

locations = [
    [17.3850, 78.4867],
    [17.3855, 78.4870],
    [17.3860, 78.4875],
]

index = 0

def get_location():
    global index
    loc = locations[index % len(locations)]
    index += 1
    return loc

loc = get_location()
print(loc)

from google.colab import files
files.upload()

import firebase_admin
from firebase_admin import credentials, db

if not firebase_admin._apps:
    cred = credentials.Certificate("pothole-1812e-firebase-adminsdk-fbsvc-6915528b86.json")

    firebase_admin.initialize_app(cred, {
        'databaseURL': 'https://pothole-1812e-default-rtdb.asia-southeast1.firebasedatabase.app/'
    })

print("✅ Firebase ready!")

import os
print(os.listdir())

from datetime import datetime

def store_pothole(lat, lon, severity):

    ref = db.reference("potholes")

    data = {
        "latitude": lat,
        "longitude": lon,
        "severity": severity,
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    ref.push(data)

# Take last window from dataset
new_window = data.iloc[-80:]

ax = new_window["accelerometerX"]
ay = new_window["accelerometerY"]
az = new_window["accelerometerZ"]
gx = new_window["gyroX"]
gy = new_window["gyroY"]
gz = new_window["gyroZ"]

acc_mag = np.sqrt(ax**2 + ay**2 + az**2)
gyro_mag = np.sqrt(gx**2 + gy**2 + gz**2)

features = {
    "ax_mean": ax.mean(),
    "ay_mean": ay.mean(),
    "az_mean": az.mean(),

    "ax_std": ax.std(),
    "ay_std": ay.std(),
    "az_std": az.std(),

    "az_max": az.max(),
    "az_min": az.min(),
    "ax_max": ax.max(),
    "ay_max": ay.max(),

    "az_rms": np.sqrt((az ** 2).mean()),

    "acc_mag_mean": acc_mag.mean(),
    "acc_mag_std": acc_mag.std(),
    "acc_mag_max": acc_mag.max(),

    "gyro_mag_mean": gyro_mag.mean(),
    "gyro_mag_std": gyro_mag.std(),

    "az_peak_to_peak": az.max() - az.min(),
    "acc_peak": acc_mag.max(),

    "az_energy": np.sum(az**2) / len(az),
    "acc_energy": np.sum(acc_mag**2) / len(acc_mag),

    "gx_mean": gx.mean(),
    "gy_mean": gy.mean(),
    "gz_mean": gz.mean(),
    "gx_std": gx.std(),
    "gy_std": gy.std(),
    "gz_std": gz.std(),
}

# Convert to DataFrame
X_new = pd.DataFrame([features])

X_new_scaled = scaler.transform(X_new)

prediction = model.predict(X_new_scaled)[0]

prediction = model.predict(X_new_scaled)[0]

if prediction == 1:

    print("🚨 Pothole detected!")

    location = get_location()
    lat, lon = location

    severity = "high" if X_new["az_rms"].values[0] > 15 else "medium"

    store_pothole(lat, lon, severity)

    print(f"Stored at: {lat}, {lon}")

from firebase_admin import db

ref = db.reference("potholes")

ref.push({
    "latitude": 17.385,
    "longitude": 78.4867,
    "severity": "high",
    "timestamp": "test"
})

print("✅ Data stored!")

def is_duplicate(new_lat, new_lon, existing_data):

    for pothole in existing_data.values():
        dist = calculate_distance(new_lat, new_lon,
                                 pothole["latitude"],
                                 pothole["longitude"])

        if dist < 5:  # meters
            return True

    return False

# Simulated route (near your stored pothole)
user_path = [
    [17.3845, 78.4860],
    [17.3848, 78.4863],
    [17.3850, 78.4865],
    [17.3852, 78.4867],  # Near pothole
    [17.3855, 78.4870],
]

from math import radians, sin, cos, sqrt, atan2

def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6371000  # meters

    dlat = radians(lat2 - lat1)
    dlon = radians(lon2 - lon1)

    a = sin(dlat/2)**2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon/2)**2
    c = 2 * atan2(sqrt(a), sqrt(1-a))

    return R * c

def get_potholes():
    ref = db.reference("potholes")
    data = ref.get()

    if data is None:
        return []

    return list(data.values())

alerted_locations = []

def is_already_alerted(lat, lon):
    for a_lat, a_lon in alerted_locations:
        if calculate_distance(lat, lon, a_lat, a_lon) < 5:
            return True
    return False


def check_alert(user_lat, user_lon):

    potholes = get_potholes()

    for pothole in potholes:

        p_lat = pothole["latitude"]
        p_lon = pothole["longitude"]

        distance = calculate_distance(user_lat, user_lon, p_lat, p_lon)

        print(f"Distance: {distance:.2f} m")

        if distance < 50:

            if not is_already_alerted(p_lat, p_lon):
                print("🚨 ALERT: Pothole ahead!")
                alerted_locations.append((p_lat, p_lon))

import time

for loc in user_path:
    lat, lon = loc

    print(f"\n📍 User Location: {lat}, {lon}")

    check_alert(lat, lon)

    time.sleep(1)  # simulate movement

potholes = get_potholes()
print("Potholes:", potholes)

import joblib

joblib.dump(model, "pothole_model.pkl")

from google.colab import files
files.download("pothole_model.pkl")

from flask import Flask, request, jsonify
import numpy as np
import joblib

app = Flask(__name__)

# Load model
model = joblib.load("pothole_model.pkl")

@app.route("/predict", methods=["POST"])
def predict():
    try:
        data = request.get_json()
        features = np.array(data['features']).reshape(1, -1)

        prediction = model.predict(features)

        return jsonify({
            "prediction": int(prediction[0]),
            "message": "Pothole Detected" if prediction[0] == 1 else "Normal Road"
        })

    except Exception as e:
        return jsonify({"error": str(e)})

if __name__ == "__main__":
    app.run(debug=True)